// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class TestsearchLJTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  public String waitForWindow(int timeout) {
    try {
      Thread.sleep(timeout);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    Set<String> whNow = driver.getWindowHandles();
    Set<String> whThen = (Set<String>) vars.get("window_handles");
    if (whNow.size() > whThen.size()) {
      whNow.removeAll(whThen);
    }
    return whNow.iterator().next();
  }
  @Test
  public void testsearchLJ() {
    driver.get("https://www.livejournal.com/");
    driver.manage().window().setSize(new Dimension(1936, 1048));
    {
      WebElement element = driver.findElement(By.cssSelector(".s-do-item-search-btn"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.cssSelector(".s-do-item-search-btn .svgicon")).click();
    driver.findElement(By.cssSelector(".s-header-search__input-wrapper > #SearchText")).sendKeys("Электрокары");
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".s-header-search__input-wrapper > #SearchText")).sendKeys(Keys.ENTER);
    vars.put("win3823", waitForWindow(2000));
    driver.switchTo().window(vars.get("win3823").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.linkText("«АвтоВАЗ» считает необходимым индексировать утильсбор на электрокары")).click();
    vars.put("win3778", waitForWindow(2000));
    driver.switchTo().window(vars.get("win3778").toString());
    driver.switchTo().window(vars.get("win3823").toString());
    vars.put("window_handles", driver.getWindowHandles());
    driver.findElement(By.cssSelector(".rsearch-note:nth-child(10) .rsearch-note__caption > b")).click();
    vars.put("win9031", waitForWindow(2000));
    driver.switchTo().window(vars.get("win9031").toString());
    js.executeScript("window.scrollTo(0,0)");
  }
}
