package org.example;// Generated by Selenium IDE

import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class SerfrepostLJTest {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        driver = new ChromeDriver();
        js = (JavascriptExecutor) driver;
        vars = new HashMap<String, Object>();
    }

    @After
    public void tearDown() {
        driver.quit();
    }

    @Test
    public void serfrepostLJ() {
        driver.get("https://www.livejournal.com/");
        driver.manage().window().setSize(new Dimension(1936, 1048));
        driver.findElement(By.cssSelector(".post-card--big > .post-card__link")).click();
        driver.findElement(By.cssSelector(".aentry-post__socials:nth-child(2) .icon-0-2-85 path")).click();
        {
            WebElement element = driver.findElement(By.cssSelector(".aentry-post__socials:nth-child(2) .icon-0-2-85 path"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        }
        js.executeScript("window.scrollTo(0,399)");
        driver.findElement(By.cssSelector(".categories__item--popup-open > .categories__link")).click();
        driver.findElement(By.cssSelector(".categories__item--popup-open > .categories__link")).click();
        driver.findElement(By.cssSelector(".post-card--horizontal > .post-card__link")).click();
        js.executeScript("window.scrollTo(0,392)");
        driver.findElement(By.cssSelector(".aentry-post__socials:nth-child(8) .icon-0-2-69 path:nth-child(1)")).click();
        js.executeScript("window.scrollTo(0,3855)");
        driver.findElement(By.cssSelector(".aentry-post__socials:nth-child(2) .icon-0-2-85 .svgicon")).click();
    }
}
