
// Generated by Selenium IDE
package org.example.HW3;

import org.example.BaseClass;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class AuthorizationLJTest extends BaseClass {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Test
    public void authorizationLJ() {
        open("https://www.livejournal.com/");
        driver.manage().window().setSize(new Dimension(974, 523));
            WebElement element = driver.findElement(By.cssSelector(".s-header-item__link--checklist"));
            Actions builder = new Actions(driver);
            builder.moveToElement(element).perform();
        driver.findElement(By.cssSelector("//a[contains(text(), 'Войти')]")).click();
        driver.findElement(By.id("user")).click();
        driver.findElement(By.id("user")).sendKeys("Vasiliy_Pup123");
        driver.findElement(By.id("lj_loginwidget_password")).click();
        driver.findElement(By.id("lj_loginwidget_password")).sendKeys("Qwerasdf_1234");
        driver.findElement(By.name("action:login")).click();
    }

}
