package org.example.HW3;// Generated by Selenium IDE

import org.example.BaseClass;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;

import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;

public class CreatenewPostLJTest extends BaseClass {
    private WebDriver driver;
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        initDriver();
        js = (JavascriptExecutor) webDriver;
        vars = new HashMap<String, Object>();
    }

    @Test
    public void createnewPostLJ() {
        webDriver.get("https://www.livejournal.com/");
        webDriver.manage().window().setSize(new Dimension(974, 523));
        {
            WebElement element = webDriver.findElement(By.cssSelector(".s-header-item__link--checklist"));
            Actions builder = new Actions(webDriver);
            builder.moveToElement(element).perform();
        }
        webDriver.findElement(By.cssSelector(".s-header-item__link--login")).click();
        webDriver.findElement(By.id("user")).click();
        webDriver.findElement(By.id("user")).sendKeys("Vasiliy_Pup123");
        webDriver.findElement(By.id("lj_loginwidget_password")).click();
        webDriver.findElement(By.id("lj_loginwidget_password")).sendKeys("Qwerasdf_1234");
        webDriver.findElement(By.name("action:login")).click();

        webDriver.manage().window().setSize(new Dimension(1936, 1048));
        webDriver.findElement(By.cssSelector(".s-header-item-post--short")).click();
        webDriver.findElement(By.cssSelector(".short-post-toolbar__item:nth-child(3) span")).click();
        webDriver.switchTo().frame(3);
        webDriver.findElement(By.cssSelector(".text-0-2-59")).click();
        webDriver.findElement(By.cssSelector(".text-0-2-59")).sendKeys("Новый пост");
        webDriver.findElement(By.cssSelector(".public-DraftStyleDefault-block")).click();
        webDriver.findElement(By.cssSelector(".text-0-2-59")).sendKeys("Новый Пост");
        webDriver.findElement(By.cssSelector(".notranslate")).click();
        {
            WebElement element = webDriver.findElement(By.cssSelector(".notranslate"));
            js.executeScript("if(arguments[0].contentEditable === 'true') {arguments[0].innerText = '<div data-contents=\"true\"><div class=\"contentEditableHelper beforeAll\" style=\"height: 1px; overflow: hidden; font-size: 0px; opacity: 0;\"></div><div class=\"aentry-post__block--unstyled\" data-block=\"true\" data-editor=\"djs2u\" data-offset-key=\"16gg0-0-0\"><div data-offset-key=\"16gg0-0-0\" class=\"public-DraftStyleDefault-block public-DraftStyleDefault-ltr\"><span data-offset-key=\"16gg0-0-0\"><span data-text=\"true\">Hello world!</span></span></div></div><div class=\"contentEditableHelper afterAll\" data-offset-key=\"16gg0-0-0\" style=\"height: 1px; overflow: hidden; font-size: 0px; opacity: 0;\"></div></div>'}", element);
        }
        webDriver.findElement(By.cssSelector(".submitBtn-0-2-77 > .rootIn-0-2-95")).click();
    }

    @After
    public void tearDown() {
        webDriver.quit();
    }
}
