package org.example.HW3;// Generated by Selenium IDE

import org.example.BaseClass;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import utils.BeforeClass;

import java.util.*;

public class TestSearchLJTest extends BaseClass {
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Before
    public void setUp() {
        initDriver();
        js = (JavascriptExecutor) webDriver;
    }


       public String waitForWindow(int timeout) {
        try {
            Thread.sleep(timeout);
        } catch (InterruptedException e) {
            e.printStackTrace();
        }
        Set<String> whNow = webDriver.getWindowHandles();
        Set<String> whThen = (Set<String>) vars.get("window_handles");
        if (whNow.size() > whThen.size()) {
            whNow.removeAll(whThen);
        }
        return whNow.iterator().next();
    }

    @Test
    public void testsearchLJ() {
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        webDriver.get("https://www.livejournal.com/");
        webDriver.manage().window().setSize(new Dimension(1936, 1048));
        WebElement element = webDriver.findElement(By.cssSelector(".s-do-item-search-btn"));
        Actions builder = new Actions(webDriver);
        builder.moveToElement(element).perform();
        webDriver.findElement(By.cssSelector(".s-do-item-search-btn .svgicon")).click();
        webDriver.findElement(By.cssSelector(".s-header-search__input-wrapper > #SearchText")).sendKeys("Электрокары");
        webDriver.findElement(By.cssSelector(".s-header-search__input-wrapper > #SearchText")).sendKeys(Keys.ENTER);
        webDriver.switchTo().window(vars.get("win3823").toString());
    }

    @After
    public void tearDown() {
        webDriver.quit();
    }
}
