package org.example.HW3;// Generated by Selenium IDE

import org.example.BaseClass;
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;

import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Keys;
import utils.BeforeClass;

import java.util.*;

public class TestSearchLJTest extends BaseClass {
    private Map<String, Object> vars;
    JavascriptExecutor js;

    @Test
    public void testsearchLJ() {
        try {
            Thread.sleep(5000);
        } catch (InterruptedException e) {
            throw new RuntimeException(e);
        }
        open("https://www.livejournal.com/");
        driver.manage().window().setSize(new Dimension(1936, 1048));
        WebElement element = driver.findElement(By.cssSelector(".s-do-item-search-btn"));
        Actions builder = new Actions(driver);
        builder.moveToElement(element).perform();
        driver.findElement(By.cssSelector(".s-do-item-search-btn .svgicon")).click();
        driver.findElement(By.cssSelector(".s-header-search__input-wrapper > #SearchText")).sendKeys("Электрокары");
        driver.findElement(By.cssSelector(".s-header-search__input-wrapper > #SearchText")).sendKeys(Keys.ENTER);
        driver.switchTo().window(vars.get("win3823").toString());
    }

}
